// Copyright (c) 2018 Kentaro Wada

#ifndef ROS_ROS_OBJSLAMPP_YCB_VIDEO_INCLUDE_ROS_OBJSLAMPP_YCB_VIDEO_UTILS_LOG_H_
#define ROS_ROS_OBJSLAMPP_YCB_VIDEO_INCLUDE_ROS_OBJSLAMPP_YCB_VIDEO_UTILS_LOG_H_

#define ANSI_COLOR_RED     "\x1b[31;1m"
#define ANSI_COLOR_GREEN   "\x1b[32;1m"
#define ANSI_COLOR_YELLOW  "\x1b[33;1m"
#define ANSI_COLOR_BLUE    "\x1b[34;1m"
#define ANSI_COLOR_MAGENTA "\x1b[35;1m"
#define ANSI_COLOR_CYAN    "\x1b[36;1m"
#define ANSI_COLOR_WHITE   "\x1b[37;1m"
#define ANSI_COLOR_RESET   "\x1b[0m"

#define ROS_INFO_RED(str, ...) \
  ROS_INFO(ANSI_COLOR_RED str ANSI_COLOR_RESET, ##__VA_ARGS__)
#define ROS_INFO_GREEN(str, ...) \
  ROS_INFO(ANSI_COLOR_GREEN str ANSI_COLOR_RESET, ##__VA_ARGS__)
#define ROS_INFO_YELLOW(str, ...) \
  ROS_INFO(ANSI_COLOR_YELLOW str ANSI_COLOR_RESET, ##__VA_ARGS__)
#define ROS_INFO_BLUE(str, ...) \
  ROS_INFO(ANSI_COLOR_BLUE str ANSI_COLOR_RESET, ##__VA_ARGS__)
#define ROS_INFO_MAGENTA(str, ...) \
  ROS_INFO(ANSI_COLOR_MAGENTA str ANSI_COLOR_RESET, ##__VA_ARGS__)
#define ROS_INFO_CYAN(str, ...) \
  ROS_INFO(ANSI_COLOR_CYAN str ANSI_COLOR_RESET, ##__VA_ARGS__)
#define ROS_INFO_WHITE(str, ...) \
  ROS_INFO(ANSI_COLOR_WHITE str ANSI_COLOR_RESET, ##__VA_ARGS__)

#define ROS_INFO_STREAM_RED(...) \
  ROS_INFO_STREAM(ANSI_COLOR_RED << __VA_ARGS__ << ANSI_COLOR_RESET)
#define ROS_INFO_STREAM_GREEN(...) \
  ROS_INFO_STREAM(ANSI_COLOR_GREEN << __VA_ARGS__ << ANSI_COLOR_RESET)
#define ROS_INFO_STREAM_YELLOW(...) \
  ROS_INFO_STREAM(ANSI_COLOR_YELLOW << __VA_ARGS__ << ANSI_COLOR_RESET)
#define ROS_INFO_STREAM_BLUE(...) \
  ROS_INFO_STREAM(ANSI_COLOR_BLUE << __VA_ARGS__ << ANSI_COLOR_RESET)
#define ROS_INFO_STREAM_MAGENTA(...) \
  ROS_INFO_STREAM(ANSI_COLOR_MAGENTA << __VA_ARGS__ << ANSI_COLOR_RESET)
#define ROS_INFO_STREAM_CYAN(...) \
  ROS_INFO_STREAM(ANSI_COLOR_CYAN << __VA_ARGS__ << ANSI_COLOR_RESET)
#define ROS_INFO_STREAM_WHITE(...) \
  ROS_INFO_STREAM(ANSI_COLOR_WHITE << __VA_ARGS__ << ANSI_COLOR_RESET)

#endif  // ROS_ROS_OBJSLAMPP_YCB_VIDEO_INCLUDE_ROS_OBJSLAMPP_YCB_VIDEO_UTILS_LOG_H_
