#!/usr/bin/env python

import mistune


with open('README.md.in') as f:
    top = mistune.markdown(f.read(), escape=False)
    top = '<!-- DO NOT EDIT THIS FILE MANUALLY. -->\n' + top
    top = top + '<h2>Examples</h2>\n'

with open('examples/ycb_video/README.md') as f:
    # -1
    sub = mistune.markdown(f.read(), escape=False)
    sub = sub.replace('h5>', 'h6>')
    sub = sub.replace('h4>', 'h5>')
    sub = sub.replace('h3>', 'h4>')
    sub = sub.replace('h2>', 'h3>')
    sub = sub.replace('h1>', 'h2>')
    top = top + '\n' + sub

with open('examples/ycb_video/multi_view_pose_estimation/README.md') as f:
    # -2
    subsub = mistune.markdown(f.read(), escape=False)
    subsub = subsub.replace('h4>', 'h6>')
    subsub = subsub.replace('h3>', 'h5>')
    subsub = subsub.replace('h2>', 'h4>')
    subsub = subsub.replace('h1>', 'h3>')
    top = top + '\n' + subsub

with open('README.md', 'w') as f:
    f.write(top)
